### login
POST http://localhost:8080/v1/user/login
Content-Type: application/json

{
  "phone": "0612345678",
  "password": "topSecret"
}

### get all users
GET http://localhost:8080/v1/user
Accept: application/json
Authorization: Bearer {{token}}

### get single user
GET http://localhost:8080/v1/user/857e27ae-e37a-11ee-8e67-4a29f78ba46f
Accept: application/json
Authorization: Bearer {{token}}

### get current user
GET http://localhost:8080/v1/user/current_user
Accept: application/json
Authorization: Bearer {{token}}

### register user
POST http://localhost:8080/v1/user/register
Content-Type: application/json

{
  "name": "zinzin",
  "phone": "0634349645",
  "role": "USER",
  "password": "hell123"
}

### update user
PUT http://localhost:8080/v1/user/2606451c-e37b-11ee-be5c-4a29f78ba46f
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "eerr"
}

### delete user
DELETE http://localhost:8080/v1/user/aa6590cc-d081-11ee-b45c-4a29f78ba46e
Authorization: Bearer {{token}}

### forget pass
POST http://localhost:8080/v1/user/forget_pass
Content-Type: application/json

{
  "phone": "0635248740"
}

### reset pass
POST http://localhost:8080/v1/user/reset_pass
Content-Type: application/json

{
  "code": "221945",
  "password": "aeiou123",
  "confirm_password": "aeiou123"
}

### logout
GET http://localhost:8080/v1/user/logout
Authorization: Bearer {{token}}

### /
GET http://localhost:8080

### access_token
GET http://localhost:8080/oauth/validate_token?access_token=eyJhbGciOiJIUzUxMiIsImtpZCI6Imp3dCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIyMjIyMjIiLCJleHAiOjE3MDc1NjA0NzAsInN1YiI6IjQ5ZjJiNDhjLWM3ZWQtMTFlZS1hZWQyLTRhMjlmNzhiYTQ2ZiJ9.mxcJKdAscZ45rZhTQHEOBew-b8foAL1bnzZbAc0wCH4ikzScTiKEp5KbvgLR8wCRgrN63lOkF03ccmNwcrPolQ

### token endpoint
GET http://localhost:8080/oauth/token