### get all users
GET http://localhost:8080/v1/users
Accept: application/json
Authorization: Bearer {{token}}

### get single user
GET http://localhost:8080/v1/user/4d501aca-c7ed-11ee-aed2-4a29f78ba46f
Accept: application/json
Authorization: Bearer {{token}}

### get current user
GET http://localhost:8080/v1/current_user
Accept: application/json
Authorization: Bearer {{token}}

### register user
POST http://localhost:8080/v1/register
Content-Type: application/json

{
  "name": "zinzin",
  "phone": "0634349640",
  "role": "ADMIN",
  "password": "asdf"
}

### update user
PUT http://localhost:8080/v1/user/165f3376-cb2f-11ee-b228-4a29f78ba46f
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "aabbcc"
}


### delete user
DELETE http://localhost:8080/v1/user/49f2b48c-c7ed-11ee-aed2-4a29f78ba46f
Authorization: Bearer {{token}}

### login
POST http://localhost:8080/v1/login
Content-Type: application/json

{
  "phone": "0634349640",
  "password": "hell123"
}

### forget pass
POST http://localhost:8080/v1/forget_pass
Content-Type: application/json

{
  "phone": "0634349640"
}

### reset pass
POST http://localhost:8080/v1/reset_pass
Content-Type: application/json

{
  "code": "964757",
  "password": "hell123",
  "confirm_password": "hell123"
}

### logout
GET http://localhost:8080/v1/logout
Authorization: Bearer {{token}}

### /
GET http://localhost:8080

### access_token
GET http://localhost:8080/oauth/validate_token?access_token=eyJhbGciOiJIUzUxMiIsImtpZCI6Imp3dCIsInR5cCI6IkpXVCJ9.eyJhdWQiOiIyMjIyMjIiLCJleHAiOjE3MDc1NjA0NzAsInN1YiI6IjQ5ZjJiNDhjLWM3ZWQtMTFlZS1hZWQyLTRhMjlmNzhiYTQ2ZiJ9.mxcJKdAscZ45rZhTQHEOBew-b8foAL1bnzZbAc0wCH4ikzScTiKEp5KbvgLR8wCRgrN63lOkF03ccmNwcrPolQ