version: '3'

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./tmp/redis_data:/var/lib/redis/data

#  db-migrate:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: db-migrate
#    command: migrate
#    depends_on:
#      - postgres
#
#  auth-service:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: auth-service
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres


volumes:
  postgres-data:
